/**
 * Created by Rina on 9/27/16.
 */

/**
 * BIZ IMAGE
 */

//admin
var PERMISSION_CREATE_BIZ="addBiz";
var PERMISSION_UPDATE_BIZ="updateBiz";
var PERMISSION_DEL_BIZ="deleteBiz";
var PERMISSION_UPDATE_ALL_BIZ="updateAllBiz";
//admin customer
var PERMISSION_GET_CUSTOMERS="getCustomers";
var PERMISSION_CREATE_CUSTOMERS="addCustomers";
var PERMISSION_UPDATE_CUSTOMERS="updateCustomers";
var PERMISSION_DELETE_CUSTOMERS="deleteCustomers";

//biz customer
var PERMISSION_GET_BIZCUSTOMERS="getBizCustomers";
var PERMISSION_CREATE_BIZCUSTOMERS="addBizCustomers";
var PERMISSION_DEL_BIZCUSTOMERS="deleteBizCustomers";
var PERMISSION_UPDATE_BIZCUSTOMERS="updateBizCustomers";

//admin customer price
var PERMISSION_GET_CUSTOMERPRICES="getCustomerPrices";
var PERMISSION_CREATE_CUSTOMERPRICES="addCustomerPrices";
var PERMISSION_UPDATE_CUSTOMERPRICES="updateCustomerPrices";
var PERMISSION_DEL_CUSTOMERPRICES="deleteCustomerPrices";



//bizCustomerPrice
var PERMISSION_GET_BIZCUSTOMERPRICES="getBizCustomerPrices";
var PERMISSION_CREATE_BIZCUSTOMERPRICES="addBizCustomerPrices";
var PERMISSION_UPDATE_BIZCUSTOMERPRICES="updateBizCustomerPrices";
var PERMISSION_DEL_BIZCUSTOMERPRICES="deleteBizCustomerPrices";


var PERMISSION_GET_BIZPAYMENTSSETTING="getBizPaymentsSetting";
var  PERMISSION_GET_PAYMENTSSETTING="getPaymentsSetting";
var PERMISSION_POST_BIZPAYMENTSSETTING="postBizPaymentsSetting";
var PERMISSION_POST_PAYMENTSSETTING="postPaymentsSetting";
var PERMISSION_DEL_PAYMENTSSETTING="deletePaymentsSetting";
var PERMISSION_PUT_BIZPAYMENTSSETTING="postBizPaymentsSetting";

//PO module
//for channel
var PERMISSION_GET_BIZPOS="getBizPos";
var PERMISSION_CREATE_BIZPOS="createBizPos";
var PERMISSION_UPDATE_BIZPOS="updateBizPos";
var PERMISSION_DELETE_BIZPOS="deleteBizPos";
//for admin
var PERMISSION_GET_ALLPOS="getAllPos";
//for supplier
var PERMISSION_GET_SUPPLIERPOS="getSupplierPos";
var PERMISSION_UPDATE_SUPPLIERPOS="updateSupplierPos";


var PO_STATUS_PENDING="pending";
var PO_STATUS_CONFIRMED="confirmed";
var PO_STATUS_COMPLETED="completed";
var PO_STATUS_CANCELED="canceled";

var PO_ITEM_STATUS_PENDING="pending";
var PO_ITEM_STATUS_SHIPPED="shipped";
var PO_ITEM_STATUS_RECEIVED="received";

var PO_ITEM_PAY_STATUS_UNPAID="unpaid";
var PO_ITEM_PAY_STATUS_PAID="paid";
var PO_ITEM_RECEIVE_STATUS_UNRECEIVED="unreceived";
var PO_ITEM_RECEIVE_STATUS_RECEIVED="received";

//bizComment
var PERMISSION_DEL_BIZCOMMENTS="deleteBizComments";

//bizImage
var PERMISSION_CREATE_BIZIMAGES="addBizImages";
var PERMISSION_DEL_BIZIMAGES="deleteBizImages";


module.exports = {
    PERMISSION_CREATE_BIZ: PERMISSION_CREATE_BIZ,
    PERMISSION_UPDATE_BIZ: PERMISSION_UPDATE_BIZ,
    PERMISSION_DEL_BIZ: PERMISSION_DEL_BIZ,
    PERMISSION_UPDATE_ALL_BIZ: PERMISSION_UPDATE_ALL_BIZ,
    PERMISSION_GET_CUSTOMERS:PERMISSION_GET_CUSTOMERS,
    PERMISSION_CREATE_CUSTOMERS:PERMISSION_CREATE_CUSTOMERS,
    PERMISSION_UPDATE_CUSTOMERS:PERMISSION_UPDATE_CUSTOMERS,
    PERMISSION_DELETE_CUSTOMERS:PERMISSION_DELETE_CUSTOMERS,


    PERMISSION_GET_BIZPOS:PERMISSION_GET_BIZPOS,
    PERMISSION_CREATE_BIZPOS:PERMISSION_CREATE_BIZPOS,
    PERMISSION_UPDATE_BIZPOS:PERMISSION_UPDATE_BIZPOS,
    PERMISSION_DELETE_BIZPOS:PERMISSION_DELETE_BIZPOS,

    PERMISSION_GET_ALLPOS:PERMISSION_GET_ALLPOS,
    PERMISSION_GET_SUPPLIERPOS:PERMISSION_GET_SUPPLIERPOS,
    PERMISSION_UPDATE_SUPPLIERPOS:PERMISSION_UPDATE_SUPPLIERPOS,

    PERMISSION_GET_BIZCUSTOMERS:PERMISSION_GET_BIZCUSTOMERS,
    PERMISSION_CREATE_BIZCUSTOMERS: PERMISSION_CREATE_BIZCUSTOMERS,
    PERMISSION_DEL_BIZCUSTOMERS: PERMISSION_DEL_BIZCUSTOMERS,
    PERMISSION_UPDATE_BIZCUSTOMERS: PERMISSION_UPDATE_BIZCUSTOMERS,

    PERMISSION_CREATE_BIZCUSTOMERPRICES: PERMISSION_CREATE_BIZCUSTOMERPRICES,
    PERMISSION_UPDATE_BIZCUSTOMERPRICES:PERMISSION_UPDATE_BIZCUSTOMERPRICES,
    PERMISSION_DEL_BIZCUSTOMERPRICES: PERMISSION_DEL_BIZCUSTOMERPRICES,
    PERMISSION_GET_BIZCUSTOMERPRICES:PERMISSION_GET_BIZCUSTOMERPRICES,
    PERMISSION_GET_CUSTOMERPRICES:PERMISSION_GET_CUSTOMERPRICES,
    PERMISSION_CREATE_CUSTOMERPRICES:PERMISSION_CREATE_CUSTOMERPRICES,
    PERMISSION_UPDATE_CUSTOMERPRICES:PERMISSION_UPDATE_CUSTOMERPRICES,
    PERMISSION_DELETE_CUSTOMERPRICES:PERMISSION_DEL_CUSTOMERPRICES,

    PERMISSION_DEL_BIZCOMMENTS: PERMISSION_DEL_BIZCOMMENTS,

    PERMISSION_CREATE_BIZIMAGES: PERMISSION_CREATE_BIZIMAGES,
    PERMISSION_DEL_BIZIMAGES: PERMISSION_DEL_BIZIMAGES,
    PERMISSION_GET_BIZPAYMENTSSETTING:PERMISSION_GET_BIZPAYMENTSSETTING,
    PERMISSION_POST_PAYMENTSSETTING:PERMISSION_POST_PAYMENTSSETTING,
    PERMISSION_GET_PAYMENTSSETTING: PERMISSION_GET_PAYMENTSSETTING,

    PERMISSION_POST_BIZPAYMENTSSETTING:PERMISSION_POST_BIZPAYMENTSSETTING,
    PERMISSION_DEL_PAYMENTSSETTING:PERMISSION_DEL_PAYMENTSSETTING,
    PERMISSION_PUT_BIZPAYMENTSSETTING:PERMISSION_PUT_BIZPAYMENTSSETTING,

    PO_STATUS_PENDING:PO_STATUS_PENDING,
    PO_STATUS_COMPLETED:PO_STATUS_COMPLETED,
    PO_STATUS_CANCELED: PO_STATUS_CANCELED,
    PO_STATUS_CONFIRMED:PO_STATUS_CONFIRMED,

    PO_ITEM_STATUS_PENDING:PO_ITEM_STATUS_PENDING,
    PO_ITEM_STATUS_SHIPPED:PO_ITEM_STATUS_SHIPPED,
    PO_ITEM_STATUS_RECEIVED:PO_ITEM_STATUS_RECEIVED,
    PO_ITEM_PAY_STATUS_UNPAID:PO_ITEM_PAY_STATUS_UNPAID,
    PO_ITEM_PAY_STATUS_PAID:PO_ITEM_PAY_STATUS_PAID,
    PO_ITEM_RECEIVE_STATUS_UNRECEIVED:PO_ITEM_RECEIVE_STATUS_UNRECEIVED,
    PO_ITEM_RECEIVE_STATUS_RECEIVED:PO_ITEM_RECEIVE_STATUS_RECEIVED
};
